define(function() {
    return {
        "properties": [{
            "name": "enableGrid",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "chartData",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "chartTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "indicatorFontColor",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "barDetails",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "xAxisTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lowValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "highValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bgColor",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableChartAnimation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableLegends",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "yAxisTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleFontSize",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "indicatorFontSize",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "legendFontSize",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableStaticPreview",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleFontColor",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "legendFontColor",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["createChart"],
        "events": []
    }
});