CREATE TABLE `DemandRequest`(
	`Category` VARCHAR(40),
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`EnrichedQTY` VARCHAR(40),
	`Forecasted` VARCHAR(40),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`Name` VARCHAR(40),
	`RequestDate` VARCHAR(40),
	`Requested` VARCHAR(40),
	`RequestedBY` VARCHAR(40),
	`SKUID` VARCHAR(40) NOT NULL,
	`SoftDeleteFlag` BOOLEAN,
	`Status` VARCHAR(40),
	`Stock` VARCHAR(40),
	PRIMARY KEY(`SKUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `DemandRequest`
	ADD CONSTRAINT `bcb7137b1b7171e84a00f560d79738` UNIQUE KEY(`SKUID`);
